const BASE_DIR = "./out";

Bun.serve({
    port: process.env.PORT || 3000,
    async fetch(req) {
        const url = new URL(req.url);
        let path = url.pathname;

        // Default root to index.html
        if (path === "/") {
            path = "/index.html";
        }

        // Try serving the requested path (e.g., /favicon.ico, /_next/static/...)
        let file = Bun.file(`${BASE_DIR}${path}`);

        // If file doesn't exist, try appending .html (Next.js static export behavior for pages like /about -> /about.html)
        if (!(await file.exists())) {
            file = Bun.file(`${BASE_DIR}${path}.html`);

            // If still not found, serve the 404.html generated by Next.js if it exists
            if (!(await file.exists())) {
                const notFound = Bun.file(`${BASE_DIR}/404.html`);
                if (await notFound.exists()) {
                    return new Response(notFound, { status: 404 });
                }
                return new Response("Not Found", { status: 404 });
            }
        }

        return new Response(file);
    },
    port: 3000
});
